{% set name = "wxutils" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 845665a38201a2c8ee19cc57ccea76c1b2393d8f1e24342c5981cf1e3ab55d78

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - wxpython

test:
  imports:
    - wxutils

about:
  home: https://github.com/newville/wxutils
  license: BSD
  license_file: LICENSE
  summary: Utilities and convenience classes and functions for wxPython

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
