{% set name = "wxutils" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82f667a0d6606988d49b98cc3987566fb278776b4e6f97b9b0ba0e08ee639b01

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - wxpython

test:
  imports:
    - wxutils

about:
  home: https://github.com/newville/wxutils
  license: BSD
  license_file: LICENSE
  summary: Utilities and convenience classes and functions for wxPython

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
