{% set name = "wxutils" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df8c82645ca5708cbe3f065abf39e925865bb5eceadf983a3d06a89bb35748dd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - wxpython

test:
  imports:
    - wxutils

about:
  home: https://github.com/newville/wxutils
  license: BSD
  license_file: LICENSE
  summary: Utilities and convenience classes and functions for wxPython

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
